image: node:18.15

stages:
  - lint
  - build
#  - test

cache:
  paths:
    - node_modules/

before_script:
  - npm install

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
  runner: course-registration-runner

#test:
#  stage: test
#  script:
#    - npm run test
