image: node:18.15

stages:
  - lint
  - build

cache:
  paths:
    - back-end/node_modules/
    - application/node_modules/

.backend-before-script: &backend-before-script
  - cd back-end/
  - npm install

.frontend-before-script: &frontend-before-script
  - cd application/
  - npm install

backend-lint:
  stage: lint
  before_script:
    - *backend-before-script
  script:
    - npm run lint
  tags:
    - shared-fi

frontend-lint:
  stage: lint
  before_script:
    - *frontend-before-script
  script:
    - npm run lint
  tags: 
    - shared-fi

backend-build:
  stage: build
  needs:
    - backend-lint
  before_script:
    - *backend-before-script
  script:
    - npm run build
  tags:
    - shared-fi

frontend-build:
  stage: build
  needs:
    - frontend-lint
  before_script:
    - *frontend-before-script
  script:
    - npm run build
  tags: 
    - shared-fi
