image: node:18.15

stages:
  - dev

cache:
  paths:
    - node_modules/

.backend_template:
  before_script:
    - cd back-end/
    - npm install

.frontend_template:
  before_script:
    - cd application/
    - npm install

backend-lint:
  extends: .backend_template
  stage: dev
  script:
    - cd application/
    - npm run lint
  tags:
    - shared-fi

backend-build:
  extends: .backend_template
  stage: dev
  script:
    - cd application/
    - npm run build
  tags:
    - shared-fi

backend-test:
  extends: .backend_template
  stage: dev
  script:
    - cd application/
    - npm run test
  tags:
    - shared-fi

frontend-lint:
  extends: .frontend_template
  stage: dev
  script:
    - cd back-end/
    - npm run lint
  tags: 
    - shared-fi

frontend-build:
  extends: .frontend_template
  stage: dev
  script:
    - cd back-end/
    - npm run build
  tags: 
    - shared-fi

frontend-test:
  extends: .frontend_template
  stage: dev
  script:
    - cd back-end/
    - npm run test
  tags:
    - shared-fi