image: node:18.15

stages:
  - backend-dev
  - frontend-dev

cache:
  paths:
    - node_modules/

backend-lint:
  stage: backend-dev
  script:
    - cd application
    - npm run lint
  tags:
    - shared-fi

backend-build:
  stage: backend-dev
  script:
    - cd application
    - npm run build
  tags:
    - shared-fi

backend-test:
  stage: backend-dev
  script:
    - cd application
    - npm run test
  tags:
    - shared-fi

frontend-lint:
  stage: frontend-dev
  script:
    - cd application
    - npm run lint
  tags: 
    - shared-fi

frontend-build:
  stage: frontend-dev
  script:
    - cd application
    - npm run build
  tags: 
    - shared-fi

frontend-test:
  stage: frontend-dev
  script:
    - cd application
    - npm run test
  tags:
    - shared-fi