image: node:18.15

stages:
  - lint
  - build
#  - test

cache:
  paths:
    - node_modules/

before_script:
  - cd application
  - npm install

lint:
  stage: lint
  script:
    - npm run lint
  tags: 
    - shared-fi

build:
  stage: build
  script:
    - npm run build
  tags: 
    - shared-fi

#test:
#  stage: test
#  script:
#    - npm run test
