image: node:18.15

stages:
  - dev

cache:
  paths:
    - node_modules/

before_script:
  - cd application
  - npm install

lint:
  stage: dev
  script:
    - npm run lint
  tags: 
    - shared-fi

build:
  stage: dev
  script:
    - npm run build
  tags: 
    - shared-fi

test:
  stage: dev
  script:
    - npm run test
  tags:
    - shared-fi