version: '0.1'
name: postgres-database
services:
  db2:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=courses
      - POSTGRES_PASSWORD=courses
      - POSTGRES_DB=courses
    ports:
      - '5432:5432'
    volumes: 
      - db2:/var/lib/postgresql/data
volumes:
  db2:
    driver: local
